Running generator and checking for diff as part of build

diff --git a/.github/workflows/build-ruby-generator.yml b/.github/workflows/build-ruby-generator.yml
--- a/.github/workflows/build-ruby-generator.yml
+++ b/.github/workflows/build-ruby-generator.yml
@@ -14,3 +14,19 @@ jobs:
 
     - run: bin/setup
     - run: bin/lint
+
+    - name: Generate packages
+      run: ruby lib/generate_packages.rb
+
+    - name: Check for differences in packages
+      run: |
+        if ! git diff --quiet HEAD packages; then
+          echo
+          echo "Git diff:"
+          git diff packages
+          echo
+          echo "*** Error ***"
+          echo "*** Detected code differences in a package ***"
+          echo "*** Please run generator and commit the results ***"
+          exit 1
+        fi
